### ISSUE TITLE
Clean Genres

### ISSUE THREAD

**Issue by Iliaromanov** [Iliaromanov/Google-Play-App-Rating-Prediction#10]
Since the Genres column consists of semicolon-separated arrays/lists (not sure what they're actually called) we should find a way to consider each individual genre in the list. 

I am not really sure how or when we should do this.

Maybe create a duplicate row for each genre in the list for that row??

We could drop Genres all together if this is too difficult and just use Category instead

**Comment by ppkgtmm** [comment]
I would like to create a PR for this issue
but cannot

**Comment by Iliaromanov** [comment]
we're dropping Genres
